### ISSUE TITLE
Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jre8:1.2.0 in react-native": "0.57.0" project

### ISSUE THREAD

**Issue by ramavadhmaurya** [ramavadhmaurya/ReactNativeAssignmentShowCase1#1]
I am facing this issue when i am going to run my react native project in android with given version or React Native project : 
**"react": "16.5.0",
"react-native": "0.57.0" version.**

### **My package.json file look like is :** 

{
  "name": "npm_Demo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "events": "^3.0.0",
    "react": "16.5.0",
    "react-native": "0.57.0",
    "react-navigation": "^2.14.2",
    "react-redux": "^5.0.7"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.45.3",
    "react-test-renderer": "16.5.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

### **And my root build.gradle file is:** 

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        jcenter()
        google()
    
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        google()
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}

Please some buddy help me to find out the problem.

**Comment by ramavadhmaurya** [comment]
I got the Resolution by my self.

I have done some changes in my build.gradle file and now it's look like :+1:  

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        jcenter()
        google()
        maven { url "http://jcenter.bintray.com"}   //I have added this line because, according to my version 
                                                                          //"3.1.4" in build.gradle will be downloadable from here.
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven { url "https://jitpack.io" }   //I have added this line 
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        google()
    }
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}

**Comment by kkiran16** [comment]
I too came across similar issue and your fix made my day. Thanks a lot.

**Comment by mohsen-hassani** [comment]
Thanks, it works for me!
